name: Build and Test

on:
  push:
    branches: ['master', 'beta']
  pull_request:
    branches: ['master', 'beta']

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2

      - run: |
          pnpm install
          pnpm run build
          pnpm run test

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
